### ISSUE TITLE
Update for 0.37 release

### ISSUE THREAD

**Issue by okwme** [cosmos/peggy#117]
Would be good to have a release that is compatible with cosmos-sdk 0.37

**Comment by okwme** [comment]
# Breaking Changes to check for

- [ ] (rest) #4837 Remove /version and /node_version endpoints in favor of refactoring /node_info to also include application version info.
- [ ] All REST responses now wrap the original resource/result. The response will contain two fields: height and result.
- [ ] #3565 Updates to the governance module:
- [ ] Rename JSON field from proposal_content to content
- [ ] Rename JSON field from proposal_id to id
- [ ] Disable ProposalTypeSoftwareUpgrade temporarily
- [ ] #3775 unify sender transaction tag for ease of querying
- [ ] #4255 Add supply module that passively tracks the supplies of a chain
- [ ] Renamed x/distribution ModuleName
- [ ] Genesis JSON and CLI now use distribution instead of distr
- [ ] Introduce ModuleAccount type, which tracks the flow of coins held within a module
- [ ] Replaced FeeCollectorKeeper for a ModuleAccount
- [ ] Replaced the staking Pool, which coins are now held by the BondedPool and NotBonded module accounts
- [ ] The NotBonded module account now only keeps track of the not bonded tokens within staking, instead of the whole chain
- [ ] #3628 Replaced governance's burn and deposit accounts for a ModuleAccount
- [ ] Added a ModuleAccount for the distribution module
- [ ] Added a ModuleAccount for the mint module
- [ ] #4472 validation for crisis genesis
- [ ] #3985 ValidatorPowerRank uses potential consensus power instead of tendermint power
- [ ] #4104 Gaia has been moved to its own repository: https://github.com/cosmos/gaia
- [ ] #4104 Rename gaiad.toml to app.toml. The internal contents of the application config remain unchanged.
- [ ] #4159 create the default module patterns and module manager
- [ ] #4230 Change the type of ABCIMessageLog#MsgIndex to uint16 for proper serialization.
- [ ] #4250 BaseApp.Query() returns app's version string set via BaseApp.SetAppVersion() when handling /app/version queries instead of the version string passed as build flag at compile time.
- [ ] #4262 GoSumHash is no longer returned by the version command.
- [ ] #4263 RestServer#Start now takes read and write timeout arguments.
- [ ] #4305 GenerateOrBroadcastMsgs no longer takes an offline parameter.
- [ ] #4342 Upgrade go-amino to v0.15.0
- [ ] #4351 InitCmd, AddGenesisAccountCmd, and CollectGenTxsCmd take node's and client's default home directories as arguments.
- [ ] #4387 Refactor the usage of tags (now called events) to reflect the new ABCI events semantics:
- [ ] Move x/{module}/tags/tags.go => x/{module}/types/events.go
- [ ] Update docs/specs
- [ ] Refactor tags in favor of new Event(s) type(s)
- [ ] Update Context to use new EventManager
- [ ] (Begin|End)Blocker no longer return tags, but rather uses new EventManager
- [ ] Message handlers no longer return tags, but rather uses new EventManager
- [ ] Any component (e.g. BeginBlocker, message handler, etc...) wishing to emit an event must do so through ctx.EventManger().EmitEvent(s).
- [ ] To reset or wipe emitted events: ctx = ctx.WithEventManager(sdk.NewEventManager())
- [ ] To get all emitted events: events := ctx.EventManager().Events()
- [ ] #4437 Replace governance module store keys to use []byte instead of string.
- [ ] #4451 Improve modularization of clients and modules:
- [ ] Module directory structure improved and standardized
- [ ] Aliases autogenerated
- [ ] Auth and bank related commands are now mounted under the respective moduels
- [ ] Client initialization and mounting standardized
- [ ] #4479 Remove codec argument redundency in client usage where the CLIContext's codec should be used instead.
- [ ] #4488 Decouple client tx, REST, and ultil packages from auth. These packages have been restructured and retrofitted into the x/auth module.
- [ ] #4521 Flatten x/bank structure by hiding module internals.
- [ ] #4525 Remove --cors flag, the feature is long gone.
- [ ] #4536 The /auth/accounts/{address} now returns a height in the response.
- [ ] The account is now nested under account.
- [ ] #4543 Account getters are no longer part of client.CLIContext() and have now moved to reside in the auth-specific AccountRetriever.
- [ ] #4588 Context does not depend on x/auth anymore. client/context is stripped out of the following features:
- [ ] GetAccountDecoder()
- [ ] CLIContext.WithAccountDecoder()
- [ ] CLIContext.WithAccountStore()
- [ ] x/auth.AccountDecoder is unnecessary and consequently removed.
- [ ] #4602 client/input.{Buffer,Override}Stdin() functions are removed. Thanks to cobra's new release they are now redundant.
- [ ] #4633 Update old Tx search by tags APIs to use new Events nomenclature.
- [ ] #4649 Refactor x/crisis as per modules new specs.
- [ ] #3685 The default signature verification gas logic (DefaultSigVerificationGasConsumer) now specifies explicit key types rather than string pattern matching. This means that zones that depended on string matching to allow other keys will need to write a custom SignatureVerificationGasConsumer function.
- [ ] #4663 Refactor bank keeper by removing private functions
- [ ] InputOutputCoins, SetCoins, SubtractCoins and AddCoins are now part of the SendKeeper instead of the Keeper interface
- [ ] (tendermint) #4721 Upgrade Tendermint to v0.32.1

**Comment by okwme** [comment]
never mind seems up to date to 1f4f20c3af8a
