### ISSUE TITLE
Update for 0.38 release

### ISSUE THREAD

**Issue by okwme** [cosmos/peggy#118]
Cosmos-SDK 0.38 has been released
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.38.0
Would be good to have a peggy release that was in sync

**Comment by okwme** [comment]
# State Machine Breaking
- [ ] (genesis) #5506 The x/distribution genesis state now includes params instead of individual parameters.
- [ ] (genesis) #5017 The x/genaccounts module has been deprecated and all components removed except the legacy/ package. This requires changes to the genesis state. Namely, accounts now exist under app_state.auth.accounts. The corresponding migration logic has been implemented for v0.38 target version. Applications can migrate via:
- [ ] $ {appd} migrate v0.38 genesis.json.
- [ ] (modules) #5299 Handling of ABCIEvidenceTypeDuplicateVote during BeginBlock along with the corresponding parameters (MaxEvidenceAge) have moved from the x/slashing module to the x/evidence module.
# API Breaking Changes
- [ ] (modules) #5506 Remove individual setters of x/distribution parameters. Instead, follow the module spec in getting parameters, setting new value(s) and finally calling SetParams.
- [ ] (types) #5495 Remove redundant (Must)Bech32ify* and (Must)Get*KeyBech32 functions in favor of (Must)Bech32ifyPubKey and (Must)GetPubKeyFromBech32 respectively, both of which take a Bech32PubKeyType (string).
- [ ] (types) #5430 DecCoins#Add parameter changed from DecCoins to ...DecCoin, Coins #Add parameter changed from Coins to ...Coin.
- [ ] (baseapp/types) #5421 The Error interface (types/errors.go) has been removed in favor of the concrete type defined in types/errors/ which implements the standard error interface. As a result, the Handler and Querier implementations now return a standard error.
- [ ] Within BaseApp, runTx now returns a (GasInfo, *Result, error) tuple and runMsgs returns a (*Result, error) tuple. A reference to a Result is now used to indicate success whereas an error signals an invalid message or failed message execution. As a result, the fields Code, Codespace, GasWanted, and GasUsed have been removed the Result type. The latter two fields are now found in the GasInfo type which is always returned regardless of execution outcome.
- [ ] Note to developers: Since all handlers and queriers must now return a standard error, the types/errors/ package contains all the relevant and pre-registered errors that you typically work with. A typical error returned will look like sdkerrors.Wrap(sdkerrors.ErrUnknownRequest, "..."). You can retrieve relevant ABCI information from the error via ABCIInfo.
- [ ] (client) #5442 Remove client/alias.go as it's not necessary and components can be imported directly from the packages.
- [ ] (store) #4748 The CommitMultiStore interface now requires a SetInterBlockCache method. Applications that do not wish to support this can simply have this method perform a no-op.
- [ ] (modules) #4665 Refactored x/gov module structure and dev-UX:
- [ ] Prepare for module spec integration
- [ ] Update gov keys to use big endian encoding instead of little endian
- [ ] (modules) #5017 The x/genaccounts module has been deprecated and all components removed except the legacy/ package.
- [ ] #4486 Vesting account types decoupled from the x/auth module and now live under x/auth/vesting. Applications wishing to use vesting account types must be sure to register types via RegisterCodec under the new vesting package.
- [ ] #4486 The NewBaseVestingAccount constructor returns an error if the provided arguments are invalid.
- [ ] (x/auth) #5006 Modular AnteHandler via composable decorators:
- [ ] The AnteHandler interface now returns (newCtx Context, err error) instead of (newCtx Context, result sdk.Result, abort bool)
- [ ] The NewAnteHandler function returns an AnteHandler function that returns the new AnteHandler interface and has been moved into the auth/ante directory.
- [ ] ValidateSigCount, ValidateMemo, ProcessPubKey, EnsureSufficientMempoolFee, and GetSignBytes have all been removed as public functions.
- [ ] Invalid Signatures may return InvalidPubKey instead of Unauthorized error, since the transaction will first hit SetPubKeyDecorator before the SigVerificationDecorator runs.
- [ ] StdTx#GetSignatures will return an array of just signature byte slices [][]byte instead of returning an array of StdSignature structs. To replicate the old behavior, use the public field StdTx.Signatures to get back the array of StdSignatures []StdSignature.
- [ ] (modules) #5299 HandleDoubleSign along with params MaxEvidenceAge and DoubleSignJailEndTime have moved from the x/slashing module to the x/evidence module.
- [ ] (keys) #4941 Keybase concrete types constructors such as NewKeyBaseFromDir and NewInMemory now accept optional parameters of type KeybaseOption. These optional parameters are also added on the keys sub-commands functions, which are now public, and allows these options to be set on the commands or ignored to default to previous behavior.
- [ ] #5547 NewKeyBaseFromHomeFlag constructor has been removed.
- [ ] #5439 Further modularization was done to the keybase package to make it more suitable for use with different key formats and algorithms:
- [ ] The WithKeygenFunc function added as a KeybaseOption which allows a custom bytes to key implementation to be defined when keys are created.
- [ ] The WithDeriveFunc function added as a KeybaseOption allows custom logic for deriving a key from a mnemonic, bip39 password, and HD Path.
- [ ] BIP44 is no longer build into keybase.CreateAccount(). It is however the default when using the client/keys add command.
- [ ] SupportedAlgos and SupportedAlgosLedger functions return a slice of SigningAlgos that are supported by the keybase and the ledger integration respectively.
- [ ] (simapp) #5419 The helpers.GenTx() now accepts a gas argument.
- [ ] (baseapp) #5455 A sdk.Context is now passed into the router.Route() function.
# Client Breaking Changes
- [ ] (rest) #5270 All account types now implement custom JSON serialization.
- [ ] (rest) #4783 The balance field in the DelegationResponse type is now sdk.Coin instead of sdk.Int
- [ ] (x/auth) #5006 The gas required to pass the AnteHandler has increased significantly due to modular AnteHandler support. Increase GasLimit accordingly.
- [ ] (rest) #5336 MsgEditValidator uses description instead of Description as a JSON key.
- [ ] (keys) #5097 Due to the keybase -> keyring transition, keys need to be migrated. See keys migrate command for more info.
- [ ] (x/auth) #5424 Drop decode-tx command from x/auth/client/cli, duplicate of the decode command.

**Comment by okwme** [comment]
never mind seems up to date to 1f4f20c3af8a

**Comment by okwme** [comment]
I see it's not finished actually

**Comment by ethanfrey** [comment]
Yes, I'd love to see more code coalesce on 0.38 (rather than various states of master), so we can start connecting modules with a common api
